### ISSUE TITLE
Images (files in general?) handled differently with single and nested (repeated) elements

### ISSUE THREAD

**Issue by netbrothers-tr** [Gernott/mask#192]
## Versions

I've tested this with TYPO 3 8.7.17 and Mask 3.3.1 (latest offered by TER).

## Description

If a Mask element uses the image field, as in this example

```json
"myelement": {
	"label": "My Element",
	"key": "myelement",
	"shortLabel": "My Element",
	"description": "My Element",
	"icon": "fa-apple",
	"color": "#ffffff",
	"columns": [
		"image",
		"header"
	],
	"labels": [
		"Bild",
		"Name"
	]
},
```

and another Mask element as in this example

```json
"myelement_set": {
	"label": "Group of My Element",
	"key": "myelement_set",
	"shortLabel": "Group of My Element",
	"description": "Group of My Element",
	"icon": "fa-archive",
	"color": "#ffffff",
	"labels": [
		"My Element"
	],
	"columns": [
		"tx_mask_myelement_item"
	]
}
```
uses this element in a one to many relationship, then images get handled differently if the element is used as a single element or as a nested (repeated) element.

Used as **single element**, images are included as an array of `FileReference` objects accessible through the key `image` in the data object. However, when used as a **repeating element** the array of file references is missing in the single iteration but the `image` key (being `0` or `1`) will indicate whether or not an image is associated with the element.

I tend to see this as a bug but maybe I've overlooked something?

**Comment by butu** [comment]
I think the important difference is that one time you are using the field "image" and the other time you are using your own field "tx_mask_myelement_item". 
For your own field, mask is generating the TCA and generating the fluid variables filled with ready FAL-Objects. If you use the **image** field from TYPO3 core, TYPO3 core generates the TCA and is rendering the fluid variables, which are not return as ready FAL-Objects by default. You would want to use your {v:content.resources.fal} viewhelper here. Or since mask 4.0.0 in TYPO3 9 you can also use a Dataprocessor.
