### ISSUE TITLE
Selectbox fields "space_before_class" & "space_after_class" reset upon save

### ISSUE THREAD

**Issue by Dari4sho** [Gernott/mask#198]
Hello guys.

## Versions
Tried on TYPO 3 9.5.1 and Mask 4.0.0.

## Description
I added a Selectbox with "space_after_class" to a Mask element (existing and fresh - tried both). 
When I change the value (let's say to 'Large') and try to safe it, the value gets reset to 'None'.

The field 'header_layout' for example works without any problems.
Does anybody have an idea what's happening?

**Comment by butu** [comment]
would you mind posting your mask.json, so I can reproduce the problem? Thank you! :)

**Comment by baschny** [comment]
@butu @Dari4sho I think the problem is all fields which are part of some palette which is not in the "General" tab will have this problem. Had the same issue with the "Layout" field.

Because these fields are also editable in the other tab (in this case "Appearance"). So the TCE form has the same field twice, and the second one "wins".

Changing the padding (or the layout) in the Appearance tab works.

So if I am right - either they have to be removed from the other palette if being used in the mask element, or they should not be available to select as a "mask field".

**Comment by localhorst** [comment]
> Because these fields are also editable in the other tab (in this case "Appearance"). So the TCE form has the same field twice, and the second one "wins". (...) So if I am right - either they have to be removed from the other palette if being used in the mask element, or they should not be available to select as a "mask field".

This is exactly right, I had the same problem. If I choose a value from the dropdown "layout" in the appearance tab, my data is stored. I'd recommend choosing oder defining another field for your requirement. I switched from using layout to header_layout, for example.

@butu If possible, these fields should be removed from the palette if they are used in a mask element
