### ISSUE TITLE
Default folders don't work out of the box

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#211]
On a fresh TYPO3 9 installation, the default folders for Fluid are like: EXT:mask_project/...
This does not work, because the extension mask_project is not installed.
The next problem is, that this extension is not installable, because the file ext_emconf.php is missing.

So at the moment Mask is not usable out of the Box and the needed knowledge for making an extension.

A solution can be, that a ext_emconf.php can be created with a mouseclick (like the creation of missing folders). Ans further we need a second Button for installing it - or link to the extensionmanager.

**Comment by itschrake** [comment]
Dear Gernott, 
we currently try to update a V8 Typo3 to V9 but can't get Mask running due to the problems you described. 

May I ask you to provide an ext_emconf.php and the needed values for plugin.tx_mask.view. templateRootPath, partialRootPaths and layoutRootPaths.0 as a workaround?

I already copied the mask.json to the right place and copied the Fluid Templates to EXT:mask_project/.... 

Nevertheless I get a frontend error message that the fluid Template can not be found. The path at which mask tried to find the fluid template is not stated in the error message. Because of that I could not fix this myself.

**Comment by Gernott** [comment]
Simply set the folders in your extensionmanager.

**Comment by SicorDev** [comment]
You are suggesting to change:
EXT:mask_project/

Into:
typo3conf/ext/mask_project/

?!? At least that is what works for me. Kinda odd that mask.json just works fine with the EXT path though.

**Comment by Gernott** [comment]
EXT: paths works only, if you create a working extension and have it installed.

**Comment by Gernott** [comment]
The default paths are fixed in the next Mask release
