### ISSUE TITLE
Tabs are messed up

### ISSUE THREAD

**Issue by schrob3000** [Gernott/mask#214]
Mask 3.3.3
TYPO3 8.7.22

After saving a existing mask page template the tabs show the wrong fields.

![image](https://user-images.githubusercontent.com/1243812/50697418-78acfe80-1042-11e9-9d0f-62ffd4ab9096.png)

**Comment by schrob3000** [comment]
The Problem depends on the sorting/naming of fields and tabs.
This configuration:
![image](https://user-images.githubusercontent.com/1243812/50780836-3d116f00-12a4-11e9-945f-6583a73095e5.png)
results in
Tab "Conent-Fields" with fields "Test 0"
Tab "Register 1" with fields "Test 1" and "Test 2"
Tab "Register 2" with fields "test 1"

The generated TCA configuration is sorted alphabetically by its keys
```
--div--;Content-Fields,tx_mask_default_0,--div--;Register 1,tx_mask_default_tab1_test1,tx_mask_default_tab1_test2,--div--;Register 2,tx_mask_default_tab2_test1,--div--;Register 0
```

**Comment by mic-ha** [comment]
I confirm this behaviour and vote for a more urgent dealing with this issue
TYPO3 9.5.5
mask 4.1.0

After adding a new element the complete ordered tab and additional properties list for the page is broken. It shows correct in the UI

<img width="530" alt="Bild 2019-04-29 um 21 13 02" src="https://user-images.githubusercontent.com/5860392/56920502-a9b6b080-6ac3-11e9-8014-a59b64ae7717.png">

which corresponds to the json outline:

```
"columns": [
                    "tx_mask_foundationappearance",
                    "tx_mask_containerheader",
                    "tx_mask_containerinnerheader",
                    "tx_mask_navigationappearance",
                    "tx_mask_containernavigation",
                    "tx_mask_containerinnernavigation",
                    "tx_mask_heroappearance",
                    "tx_mask_containerhero",
                    "tx_mask_contentappearance",
                    "tx_mask_containercontent",
                    "tx_mask_footerappearance",
                    "tx_mask_containerfooter",
                    "tx_mask_containerinnerfooter",
                    "tx_mask_menuproperties",
                    "tx_mask_submenu"
                ],
```

But saving breaks the TCA order:

<img width="909" alt="Bild 2019-04-29 um 21 10 29" src="https://user-images.githubusercontent.com/5860392/56920654-15008280-6ac4-11e9-9d6c-9d5474e25c28.png">

which can be seen within the json too (and it does not make any sense to order all tabs together)

[excerpt]
```
"tx_mask_containernavigation": {
                "config": {
                    "autoSizeMax": "",
                    "fileFolder": "",
                    "fileFolder_extList": "",
                    "fileFolder_recursions": "",
                    "foreign_table": "",
                    "foreign_table_where": "",
                    "items": [
                        [
                            "Boxed",
                            "boxed"
                        ],
                        [
                            "Fluid",
                            "fluid"
                        ],
                        [
                            "Full",
                            "full"
                        ]
                    ],
                    "maxitems": "",
                    "renderType": "selectSingle",
                    "size": "",
                    "type": "select"
                },
                "exclude": "1",
                "key": "containernavigation",
                "l10n_mode": ""
            },
            "tx_mask_contentappearance": {
                "config": {
                    "type": "tab"
                },
                "key": "contentappearance"
            },
            "tx_mask_footerappearance": {
                "config": {
                    "type": "tab"
                },
                "key": "footerappearance"\n
            },
```

Could this be fixed soon please, because it makes it impossible to add and/or remove properties or elements during development and keep the UX in scope for i.e. pre-tests with editors.

**Comment by kurtzaugg** [comment]
Are there news on this issue?

**Comment by nhovratov** [comment]
Fix is there. Will be released in the next version soon!
