### ISSUE TITLE
a change of the field makes the field unsavable in BE

### ISSUE THREAD

**Issue by blueamerican** [Gernott/mask#257]
I make an element named "teasertext" with the field bodytext.
Then i change the field type to rowDescription, because i do not need a RTE.

Now i want to create a new record in the BE. I fill in content in the field.
But everytime i "save" the record, the content of the field teasertext disappears.

How to fix this?
TYPO3 9.5.10
mask 4.1.2

**Comment by blueamerican** [comment]
this is an issue with rowDescription:
if i fill in the content for this field in the tab "notes", i can save it.

We have the field rowDescription twice.

This is a problem.
![mask1](https://user-images.githubusercontent.com/5647051/68525005-9041bd00-02cd-11ea-93b5-b391635862dd.jpg)
![mask2](https://user-images.githubusercontent.com/5647051/68525007-9041bd00-02cd-11ea-9a9f-149cc19cac12.jpg)

**Comment by nitori** [comment]
How exactly did you modify the fields configuration?

Usually if you have a field twice in your form, it's because it was added a second time to the "showitem" field list (either directly or using `addToAllTCAtypes`).

Be sure the original location is removed first, before adding it to another place.

**Comment by blueamerican** [comment]
This issue is no longer about modifying fields.
Simply rowDescription does not work.

**Comment by nitori** [comment]
Okay, you're right. I see the issue now.

It's probably best to not use the rowDescrpition field here, because it has a special purpose in tt_content tables (it's the "description column" in tt_content defined in `ctrl/descriptionColumn`).

It's best to simply stick with bodytext and either:

- define `columnsOverrides` for your mask type in the `TCA/Overrides/tt_content.php` file, or
- simply create a new field with your preferred settings.
