### ISSUE TITLE
Error when dealing with languages

### ISSUE THREAD

**Issue by andremichaelis** [Gernott/mask#286]
To reproduce the error i created a new composer installation of typo3 and installed mask. 

On the new page i configured the language english and german. 

After that the following error message is shown in the page view:

**Return value of TYPO3\CMS\Backend\ViewHelpers\LanguageColumnViewHelper::render() must be an instance of TYPO3\CMS\Backend\View\BackendLayout\Grid\GridColumn, null returned**

I suspect that there is a connection with mask and have also tried to find out the error. unfortunately without success. i would appreciate a short feedback.

**Comment by rschaufler** [comment]
I can confirm this issue. I set up a fresh blank installation and configured additional languages. When trying to translate a page in the page module via the "Languages" option in the dropdown, this error appears.

No GridColumn is returned because it tries to find a column for colPos 999, which doesn't exist. If you add a column with colPos 999 in your backend layout, the error disappears. That's not really a fix since colPos 999 is reserved by mask for nested content as far as i know.

**Comment by rschaufler** [comment]
It seems to stem from https://github.com/Gernott/mask/commit/1f83c821837d8221ad65268d225414caff6ec3fd

A new colPos is forcefully added without actually existing in the backend layout
