### ISSUE TITLE
Mask under TYPO3 10.4 error

### ISSUE THREAD

**Issue by kuchi62** [Gernott/mask#292]
Hi,
after Installation of Mask and clicking the Mask-Button to create the Folders it comes that Error:

**Backend:**
Oops, an error occurred!
Return value of TYPO3\CMS\Extbase\Service\ImageService::getImageFromSourceString() must be an object, null returned

**Backend/Protokoll:**
`Core: Exception handler (WEB): **Uncaught TYPO3 Exception: Return value of TYPO3\CMS\Extbase\Service\ImageService::getImageFromSourceString() must be an object, null returned** | TypeError thrown in file /home/tisfsnpo/www.xxx.de/typo3_src-10.4.4/typo3/sysext/extbase/Classes/Service/ImageService.php in line 171. Requested URL: http://xxx/typo3/**index.php?route=%%2Fmodule%%2Ftools%%2FMaskMask&token=--AnonymizedToken--`

Has anybody an answer? Thank you!

TYPO3-Version	10.4.4
Webserver	Apache
PHP-Version	7.3.14
Datenbank (Default)	MySQL 5.7.29
Betriebssystem	Linux 4.19.104+49-ph

**Comment by nhovratov** [comment]
I tried this on a freshly installed typo3 and mask and can't reproduce this. You mean the "Create missing directories and files" button? Can you provide steps to reproduce or a full stack trace?

**Comment by kuchi62** [comment]
Hi Nikita,

 

the error is displayed, when i click the Mask Button (to make the next Step "Create missing directories and files" ) 

This are the installed Extensions (mask is today not installed):



 

Best Regards and Thanks.
Jens

 

Von: Nikita Hovratov <notifications@github.com> 
Gesendet: Donnerstag, 2. Juli 2020 10:16
An: Gernott/mask <mask@noreply.github.com>
Cc: kuchi62 <info@juk-webservice.de>; Author <author@noreply.github.com>
Betreff: Re: [Gernott/mask] Mask under TYPO3 10.4 error (#292)

 

I tried this on a freshly installed typo3 and mask and can't reproduce this. You mean the "Create missing directories and files" button? Can you provide steps to reproduce or a full stack trace?

**Comment by nhovratov** [comment]
Hi Jens,

seems you forgot to paste the list. Just to be sure: you had version 5 of mask installed?

**Comment by kuchi62** [comment]
Hi Nikita,

 

‚seems you forgot to paste the list‘ - what do you mean?
I use the last versions of Typo3 and mask.

 

Best Regards Jens 

 

Von: Nikita Hovratov <notifications@github.com> 
Gesendet: Donnerstag, 2. Juli 2020 11:32
An: Gernott/mask <mask@noreply.github.com>
Cc: kuchi62 <info@juk-webservice.de>; Author <author@noreply.github.com>
Betreff: Re: [Gernott/mask] Mask under TYPO3 10.4 error (#292)

 

Hi Jens,

seems you forgot to paste the list. Just to be sure: you had version 5 of mask installed?

**Comment by knflovid** [comment]
Hi,
i can confirm this problem. I am trying to let you know the steps i have done: 
I have setup a fresh Typo3 10.4.6 to setup a small project. After setting up the basic structure as ext-plugin (nothing serious, just to develop the template), I have installed Mask and first it worked quite well. I was starting to explore the new version (5.1.1), especially the backend mask as a test. Later i kicked that backend plugin again. I have created a small test mask for the frontend and everything worked quite well. Then this error occured.

(from log:)
- Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of TYPO3\CMS\Extbase\Service\ImageService::getImageFromSourceString() must be an object, null returned | TypeError thrown in file /var/www/html/typo3_src-10.4.6/typo3/sysext/extbase/Classes/Service/ImageService.php in line 171. Requested URL: http://dig.int.kn/typo3/index.php?route=%%2Fmodule%%2Ftools%%2FMaskMask&token=--AnonymizedToken--

As far as I can see this problem is not solvable via the backend. I have removed Mask from the template, deinstalled Mask in Extensions and removed it, flushed all caches, went to maintenance and worked thru the upper line of steps including PHP and cleared the tables. The CMS was then error free (in the logs). Now with an optically clear T3, new installation of Mask, same error again. Even falling back to 5.1.0 didn't help.

What keeps me wondering is: in the error msg is this line ...?route=%%2Fmodule%%2Ftools%%2F**MaskMask**&token=--AnonymizedToken-- This doubled word Mask looks at least suspicous to me.

Really love Mask, the plugin is in my view a real benefit to typo3. If I can be of any help, please let me know.

Florian

**Comment by nhovratov** [comment]
@knflovid Hi, thanks for the detailed explanation! The double word MaskMask is correct (first one is the extension name and second one the submodule name). So first it worked correctly and then you kicked out the "backend plugin". Do you mean the mask extension by "backend plugin" or your sitepackage extension?

**Comment by knflovid** [comment]
Hi @nhovratov 
Oh you are right, "kicked" made it unclear, sorry 👯 . No, via T3 Backend I've added an own backend layout with two rows and then added a select field via Mask Backend (for i.e. letting the editor switch a function to display in the frontend). This worked so far. After that, I have selected another backend layout for that page, went to Mask, trashed the backend mask and then trashed the backend layout via T3.  So, it was a classical 1-2-3-test-3-2-1; simply turning the direction. So, more or less everything was within the backend, no switching inside the sitepackage.
During further tests, I have tried to restore different backups to see what happens, if the Mask plugin is deinstalled and the Mask-Project folder is played back again. Very dirty step, but if the system doesn't find a graphics, it might be gone during operation. But this didn't help too.
Next step: Back to mama: deinstall T3, cleanup mysql and remove the folders, starting over again. 

Nikita; Спаси́бо тебе́ за по́мощь.
If i can be of further help, catch me, i am around... :)

Florian

**Comment by nhovratov** [comment]
@knflovid No, problem :) You said you "trashed the backend mask". So to make it clear: You are refering to backend layouts and adding additional fields with mask to them, right? So you didn't create any content elements? I'm asking because you can't delete backend layouts in mask backend. Only edit them.

![Screenshot_2020-07-29 New TYPO3 site  TYPO3 CMS 10 4 5](https://user-images.githubusercontent.com/19343425/88799987-ad922080-d1a7-11ea-84c3-aaab7dbf4e78.png)

We need to figure out step by step how to reproduce. I have never encountered that error so far.

1. Install mask extension
2. Create backend layout via typo3
3. Add fields to backend layout via mask editor
4. Trash the backend mask?
5. Delete backend layout
6. Error?

This is my knowledge so far.

**Comment by kuchi62** [comment]
My actions:

 

I use my own distribution. There in page.ts i added the field mask,mask_element..xy. So far how ever.

Then I added the mask extension via Extensionmanager. After that i try to use the mask-Button to autocreate the folders.

After that I got the error.

Jens

 

Von: Nikita Hovratov <notifications@github.com> 
Gesendet: Mittwoch, 29. Juli 2020 14:33
An: Gernott/mask <mask@noreply.github.com>
Cc: kuchi62 <info@juk-webservice.de>; Author <author@noreply.github.com>
Betreff: Re: [Gernott/mask] Mask under TYPO3 10.4 error (#292)

 

@knflovid <https://github.com/knflovid>  No, problem :) You said you "trashed the backend mask". So to make it clear: You are refering to backend layouts and adding additional fields with mask to them, right? So you didn't create any content elements? I'm asking because you can't delete backend layouts in mask backend. Only edit them.

 <https://user-images.githubusercontent.com/19343425/88799987-ad922080-d1a7-11ea-84c3-aaab7dbf4e78.png> 

We need to figure out step by step how to reproduce. I have never encountered that error so far.

1.	Install mask extension
2.	Create backend layout via typo3
3.	Add fields to backend layout via mask editor
4.	Trash the backend mask?
5.	Delete backend layout
6.	Error?

This is my knowledge so far.

**Comment by knflovid** [comment]
@nhovratov 
wilco, will take a till late afternoon, currently in a meeting. Need to setup a clean T3 10 first; currently the error occurs when i have installed Mask and open the Mask element the first time directly (see snapshots). I have embedded 2 snaps to see the behaviour.

Florian

![2020-07-29 14_37_07-dig  TYPO3 CMS 10 4 6](https://user-images.githubusercontent.com/46492153/88800942-3493c880-d1a9-11ea-9928-006e7383b4bd.png)
![2020-07-29 14_40_29-dig  TYPO3 CMS 10 4 6](https://user-images.githubusercontent.com/46492153/88801307-c7ccfe00-d1a9-11ea-9a25-a25bd8eafdfc.jpg)

**Comment by kuchi62** [comment]
@florian exactly this is my problem too.

 

Von: florian harms <notifications@github.com> 
Gesendet: Mittwoch, 29. Juli 2020 14:44
An: Gernott/mask <mask@noreply.github.com>
Cc: kuchi62 <info@juk-webservice.de>; Author <author@noreply.github.com>
Betreff: Re: [Gernott/mask] Mask under TYPO3 10.4 error (#292)

 

@nhovratov <https://github.com/nhovratov> 
wilco, will take a till late afternoon, currently in a meeting. Need to setup a clean T3 10 first; currently the error occurs when i have installed Mask and open the Mask element the first time directly (see snapshots). I have embedded 2 snaps to see the behaviour.

Florian

 <https://user-images.githubusercontent.com/46492153/88800942-3493c880-d1a9-11ea-9928-006e7383b4bd.png> 
 <https://user-images.githubusercontent.com/46492153/88801307-c7ccfe00-d1a9-11ea-9a25-a25bd8eafdfc.jpg>

**Comment by nhovratov** [comment]
@knflovid can you enable development mode and send me the whole stacktrace?

**Comment by florian** [comment]
Please don't @ mention me. I'm a different Florian and this generates a bunch of emails + subscribes me to this thread.

**Comment by nhovratov** [comment]
We never mentioned you? Weird.

**Comment by florian** [comment]
@kuchi62 [did](https://github.com/Gernott/mask/issues/292#issuecomment-665644354):

> @florian exactly this is my problem too.

**Comment by knflovid** [comment]
> @knflovid can you enable development mode and send me the whole stacktrace?

sure, we also can meet via ie. zoom or equal to give you a backend look... and sorry to the other Florian. Our parents might have coordinated better... :)

Florian

**Comment by nhovratov** [comment]
Hi, after a zoom session with Florian, we figured out that whats causing the issue is a missing icon in your backend layout page ts config. In his case it was the line `icon = EXT:example_extension/Resources/Public/Images/BackendLayouts/default.gif`. When you use the typo3 backend layout builder and click the button "Show PageTS-config" to copy the config, this line is beeing generated there and should be replaced with your own icon.

**Comment by markusDE97** [comment]
Hello,

i have the same error message. I create the missing icon in the affected folder. But i recieve this message
TypeError
Return value of TYPO3\CMS\Extbase\Service\ImageService::getImageFromSourceString() must be an object, null returned

What can i do?

i have already uninstalled mask, cleared cache, and reinstalled again. but to no success. The error message appears again.

My System:
Hosting on Domainfactory
T3 Version: 10.4.12
mask: 6.4.0

thank you in advance for your help

Markus

**Comment by nhovratov** [comment]
Hi Markus,

have you checked all of your Backend Layouts? Where did you put your icon in? I suppose either there is another backend layout with a missing icon or the path is wrong.
Clearing system cache should be enough too, as this is not a specific mask error.
