### ISSUE TITLE
Allow fileByUrlAllowed

### ISSUE THREAD

**Issue by luesoad** [Gernott/mask#375]
fileByUrlAllowed is not possible so far
```
$GLOBALS['TCA']['pages']['columns']['media']['config']['appearance'] = [
   'fileUploadAllowed' => false,
   'fileByUrlAllowed' => false,
];

```
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.1/Feature-84250-SeparatelyEnableDisableAddMediaByURLAndSelectUploadFiles.html

**Comment by nhovratov** [comment]
Thanks for the feature request!

**Comment by nhovratov** [comment]
Right now this feature would do nothing, because mask files are treated as normal images.
What we need is: A new option to select if the file is an image or a media file (Equivalent in TYPO3: text/image and text/media)
This can be done with radio buttons.
And then a new checkbox would appear where you can enable/disable fileByUrlAllowed. Probably it would make sense to enable it by default.

**Comment by ayacoo** [comment]
"I tend to introduce a new field type media." I think that would also be a good solution.

In the UI you could also read the online types youtube, vimeo etc. from the registry to avoid typos.

**Comment by nhovratov** [comment]
@ayacoo I would just use the `mediafile_ext` list from the DefaultConfiguration and allow to override it, just like with the normal file field.
Or you mean Mask could present checkboxes to enable/turn off youtube/vimeo ect.?

**Comment by ayacoo** [comment]
@nhovratov Yes, that's exactly what I meant. Give the user as little room as possible to make mistakes in the UI. Is of course only a personal attitude ;-)
