### ISSUE TITLE
After saving the half element fields are deleted

### ISSUE THREAD

**Issue by Thomas-TYPO3** [Gernott/mask#378]
TYPO3 10.4.12 (composer) [Update from 10.4.5]
mask 6.3.0  [Update from 5.0.1]

Over nearly 180 content elements were in the mask list. Now, after a saving, nearly the half of the elemets are missing and deleted in mask.json. When i add new text fields the new CE element isn't saved.   

I get no JS error in the console. InkognitoMode in browser.
Checked the Network if the script "Mask.js" is loaded, yes.
Have checked the valid of the mask.json, all fine.

EXT mask removed. Compare and update the database table, clear the cache.  
Reinstalled EXT mask
mask.json Backup reinsert, clear cache. Compare DB, all tables ok.
All CE's are in the mask list. 

After saving, again the half content elements are deleted. 

Downgrading to mask 5.0.3 do the same.

**Comment by nhovratov** [comment]
Hi Thomas,

can you send me your mask.json file, so I can test it?

**Comment by Thomas-TYPO3** [comment]
Hi Nikita,

thank you for your Feedback.
I send the file per DM.

**Comment by nhovratov** [comment]
@Thomas-TYPO3 
The problem is that mask creates more than 6000 form fields and everything that exceeds the `max_input_vars` limit (e.g. 1500) is ignored.
This can't be fixed with how Mask works right now.
Mask version 7 will work with VueJs for the Builder and there won't be this problem anymore.
Until then consider raising the limit for local development.

**Comment by Thomas-TYPO3** [comment]
That's it, perfect :-)
I increased the max_input_vars in php.ini, now it works.

Thanks for the fast and professional feedback.
