### ISSUE TITLE
can't get repeater fields from another page (backend layout)

### ISSUE THREAD

**Issue by rrrrpppp** [Gernott/mask#394]
I have a backend layout for the start page only with general information that should also be output on the subpages. I fetch the data as follows:

```
<v:variable.set name="website" value="{f:cObject(typoscriptObjectPath : 'lib.rootpid')}" />
<v:variable.set name="companies" value="{v:page.info(pageUid: website, field: '{data.tx_mask_dpage_companies_company}' )}" />

<f:debug>{website}</f:debug>
<f:debug>{companies}</f:debug>

<f:debug>{data.tx_mask_dpage_companies_company}</f:debug>
```
This is what comes of it:

<img width="376" alt="fluiddebug" src="https://user-images.githubusercontent.com/22800880/112379479-806f2100-8ce8-11eb-8670-eea244ee2851.png">

Shouldn't {companies} output the same as {data.tx_mask_dpage_companies_company}?

{data.tx_mask_dpage_companies_company} is a repeater field with additional fields.

It works with simple fields like text, number, but not with the repeater (array). What am I missing?

**Comment by nhovratov** [comment]
Hi Robin @rrrrpppp 

I think the problem is here: 
`<v:variable.set name="companies" value="{v:page.info(pageUid: website, field: '{data.tx_mask_dpage_companies_company}' )}" />`

The `field` option should be a string. So this would be correct:

`<v:variable.set name="companies" value="{v:page.info(pageUid: website, field: 'tx_mask_dpage_companies_company' )}" />`

And another tip: You can use f:variable since TYPO3 8.

**Comment by rrrrpppp** [comment]
Hi Nikita @nhovratov 
Thank you very much for the advice. I have tried it accordingly as a string at field.
And also with this:

`<f:variable name="companies" value="{v:page.info(pageUid: website, field: 'tx_mask_dpage_companies_company' )}" />`

Now, however, only the number of entries comes out here: 2 (integer)
<img width="232" alt="Bildschirmfoto 2021-03-27 um 13 18 32" src="https://user-images.githubusercontent.com/22800880/112720495-fe0c7a00-8efe-11eb-996c-d67c81c2cc0e.png">


Do you have any other ideas?

**Comment by nhovratov** [comment]
@rrrrpppp Have you tried with `data.tx_mask_dpage_companies_company` ?

**Comment by rrrrpppp** [comment]
@nhovratov With `data.tx_mask_dpage_companies_company` I only get NULL.

I'm on the root page, where I choose the specific backend layout for the start page to get the repeater fields from tx_mask_dpage_companies_company.

```
<f:variable name="website" value="{f:cObject(typoscriptObjectPath : 'lib.rootpid')}" />
<f:variable name="companies" value="{v:page.info(pageUid: website, field: 'tx_mask_dpage_companies_company' )}" />
<f:variable name="data_companies" value="{v:page.info(pageUid: website, field: 'data.tx_mask_dpage_companies_company' )}" />
<f:debug>{data.tx_mask_dpage_companies_company}</f:debug>
<f:debug>{companies}</f:debug>
<f:debug>{data_companies}</f:debug>
```

<img width="679" alt="Bildschirmfoto 2021-04-01 um 20 50 08" src="https://user-images.githubusercontent.com/22800880/113340354-11b74680-932c-11eb-9d83-09e40afee71e.png">

**Comment by nhovratov** [comment]
The f:variable ViewHelper can store arrays thats not the problem.
So what mask does is that it processes repeating fields and puts them into the data array of your page record.
This does only happen however for your current page, because it has to go through the FLUIDTEMPLATE cObject, where mask hooks into the DataProcessor.
When you use v:page.info it only fetches the raw data from the db.
What you would need to do is to process the data yourself. Either by creating an own ViewHelper or better add another DataProcessor which fills your current data with the data from your site root.
Have a look at the FluidTemplate XClass of Mask. There you will see fieldHelper->addInlineData() or something similar.

If you need further help I will welcome you to the ext-mask slack channel, where such matters can be discussed better.
