### ISSUE TITLE
Backend Preview

### ISSUE THREAD

**Issue by zwenn** [Gernott/mask#418]
Hi,

there is hardcoded css styles in mask/Classes/Hooks/PageLayoutViewDrawItem.php 
on line 149:
$itemContent .= '<div style="display:block; padding: 10px 0 4px 0px;border-top: 1px solid #CACACA;margin-top: 6px;" class="content_preview_' . $elementKey . '">';

If the field header is not used in an mask element there is unnecessary space and border of top of the template view in backend.

I have found this closed issue: https://github.com/Gernott/mask/issues/316
So this behavior/bug still exists.
The line 148: $headerContent = '<strong><a href="' . $editElementUrl . '">' . $elementLabel . '</a></strong><br>';
is not taken in account at all. So styling/templating of this part is difficult.

In my opinion the removment of the inline styles in line 149 gives us the chance to style this on our own.

Thank you for your help
Sven

**Comment by nhovratov** [comment]
@zwenn Hi, this is still a bug in TYPO3. See: https://forge.typo3.org/issues/91760
As soon as this is fixed, the header will be visible again and there won't be empty space.
Regarding the inline styles: I think it's a ok default. You still can style your content.
I can move it maybe into a stylesheet, instead of inline so it is easier to override.

**Comment by nhovratov** [comment]
@zwenn I moved the inline styles now into the backend.css file. This should give you the opportunity to override it more easily.
As the headerContent thing is still a TYPO3 bug, I close this issue.
You can change to legacy PageLayoutView in the feature toggles, if you really need it.
