### ISSUE TITLE
Float fields are evaluated to double2 by default

### ISSUE THREAD

**Issue by zwenn** [Gernott/mask#419]
and also the generated SQL is defined as an double.

The evaluation to double and sql field definition double should be an option.
Otherwise longer floats are not possible.

Or is there a possibility to have longer float fields?

I need them to represent location points latitude and longitude.

Thank you for your help.

Sven
<img width="447" alt="sql" src="https://user-images.githubusercontent.com/6844841/124506172-60f99100-ddcb-11eb-80db-cc7243a2e7ca.png">
<img width="382" alt="tca" src="https://user-images.githubusercontent.com/6844841/124506177-63f48180-ddcb-11eb-8c82-ddd3c25f8c49.png">

**Comment by nhovratov** [comment]
@zwenn Hi, you are right. The decimal database type is not supported yet. What you can do is, to use a normal input string field and edit mask json manually.
Replace varchar with decimal:
`decimal(24,14) DEFAULT '0.00000000000000'`

**Comment by nhovratov** [comment]
TYPO3 supports only float fields with a precision of 2 ("double2"). Right now we work on dedicated TCA types, which possibly will also include "coordinate" fields. As for now, I suggested an alternative already. Probably you don't even need a decimal field, because in most cases, you don't need to do calculations with it.
