### ISSUE TITLE
FEATURE REQUEST: support *selectTree* renderType

### ISSUE THREAD

**Issue by m41r** [Gernott/mask#424]
For example for pages or categories. 

Reference: https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/selectTree.html

**Comment by nhovratov** [comment]
@m41r Thanks, will add it to the todo list!

**Comment by nhovratov** [comment]
@m41r Hey, I added now the category field, which is available since TYPO3 v11. This is exactly like selectTree, but only for categories. My question is: Do we even need the normal selectTree anymore? There are only two possibilities for out-of-the-box hierachical data: pages and categories. I think pages can be easier selected with the group field.

What do you think?

**Comment by m41r** [comment]
@nhovratov hi, this seems solid ... to be honest, i've never used the "group" TCA field, always "select" ;) Maybe i should give it a try ...

**Comment by nhovratov** [comment]
Cool, I'll close this then for now. I you feel we need selectTree anyway, go ahead and open a new issue.
